### ISSUE TITLE
Recheck for broken links

### ISSUE THREAD

**Issue by dangpzanco** [JackKelly/climate-change-mitigation#2]
The link in the [Modelling the energy usage of buildings](https://github.com/JackKelly/climate-change-mitigation/blob/master/topics.adoc#modelling-the-energy-usage-of-buildings) subsection of the topics is broken. 

The new link is this one [here](https://teddinet.org/blog/post.php?s=2016-03-23-special-section-of-energy-buildings-advances-in-building-energy-modeling-and-simulation), I think.

So maybe, recheck some links, or make sure the [WayBack Machine](https://archive.org/web/) has a backup. 
If you have time, that is, haha.

Cheers

**Comment by JackKelly** [comment]
thanks for the bug report!  It's now fixed :)
